### ISSUE TITLE
contenu erroné

### ISSUE THREAD

**Issue by pascallegal** [etalab/datagouvfr-pages#30]
Le fichier disponible ici :
https://www.data.gouv.fr/fr/datasets/fichier-des-personnes-decedees/

contient des informations qui ne sont pas en relation avec la COVID 19, induisant les lecteurs en erreur.
en effet, le fichier ne contient pas que les décès liés au covid 19.

cordialement,

**Comment by restuccia** [comment]
Merci ! Nous avons clarifié la nature du jeu de données des personnes décédées #102ffedc02d3618c18ad8c1c528b3928c8121c1c
